
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class BayarSPP extends javax.swing.JFrame {

    /**
     * Creates new form BayarSPP
     */
    public BayarSPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Bawah = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        totalpembayarannya = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        Hitung = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        Atas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sampingkiri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tNama = new javax.swing.JTextField();
        hargaSPP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        tJanuari = new javax.swing.JRadioButton();
        tFebruari = new javax.swing.JRadioButton();
        tMaret = new javax.swing.JRadioButton();
        tApril = new javax.swing.JRadioButton();
        tMei = new javax.swing.JRadioButton();
        tJuni = new javax.swing.JRadioButton();
        tJuli = new javax.swing.JRadioButton();
        tAgustus = new javax.swing.JRadioButton();
        tSeptember = new javax.swing.JRadioButton();
        tOktober = new javax.swing.JRadioButton();
        tNovember = new javax.swing.JRadioButton();
        tDesember = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bawah.setLayout(new java.awt.BorderLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga SPP", "Bulan", "Status "
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel5.setText("Hitung : ");

        totalpembayarannya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpembayarannyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalpembayarannya)
                .addGap(19, 19, 19))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalpembayarannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Bawah.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        Hitung.setText("Hitung ");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel7.add(Hitung, gridBagConstraints);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel7.add(Simpan, gridBagConstraints);

        Reset.setText("Reset ");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel7.add(Reset, gridBagConstraints);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel7.add(Keluar, gridBagConstraints);

        Bawah.add(jPanel7, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Bawah, java.awt.BorderLayout.PAGE_END);

        Atas.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMBAYARAN SPP ");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro Black", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BIMBEL BAHASA THAILAND");

        javax.swing.GroupLayout AtasLayout = new javax.swing.GroupLayout(Atas);
        Atas.setLayout(AtasLayout);
        AtasLayout.setHorizontalGroup(
            AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtasLayout.createSequentialGroup()
                .addGroup(AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtasLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AtasLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        AtasLayout.setVerticalGroup(
            AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Atas, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nama");

        jLabel3.setText("Harga SPP : ");

        jLabel4.setText("Bulan : ");

        javax.swing.GroupLayout sampingkiriLayout = new javax.swing.GroupLayout(sampingkiri);
        sampingkiri.setLayout(sampingkiriLayout);
        sampingkiriLayout.setHorizontalGroup(
            sampingkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sampingkiriLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(sampingkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        sampingkiriLayout.setVerticalGroup(
            sampingkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sampingkiriLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel2.add(sampingkiri, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tNama)
                    .addComponent(hargaSPP, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargaSPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(4, 3));

        tJanuari.setText("Januari");
        jPanel5.add(tJanuari);

        tFebruari.setText("Februari");
        jPanel5.add(tFebruari);

        tMaret.setText("Maret");
        jPanel5.add(tMaret);

        tApril.setText("April");
        jPanel5.add(tApril);

        tMei.setText("Mei");
        tMei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMeiActionPerformed(evt);
            }
        });
        jPanel5.add(tMei);

        tJuni.setText("Juni");
        jPanel5.add(tJuni);

        tJuli.setText("Juli");
        jPanel5.add(tJuli);

        tAgustus.setText("Agustus");
        jPanel5.add(tAgustus);

        tSeptember.setText("September");
        jPanel5.add(tSeptember);

        tOktober.setText("Oktober");
        jPanel5.add(tOktober);

        tNovember.setText("November");
        jPanel5.add(tNovember);

        tDesember.setText("Desember");
        jPanel5.add(tDesember);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalpembayarannyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpembayarannyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpembayarannyaActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        String namaa = tNama.getText();
        double jumlahbulan = 0 ;

        if (tJanuari.isSelected() && tJanuari.isEnabled()) jumlahbulan ++;
        if (tFebruari.isSelected()&& tFebruari.isEnabled()) jumlahbulan ++;
        if (tMaret.isSelected()&& tMaret.isEnabled()) jumlahbulan ++;
        if (tApril.isSelected()&& tApril.isEnabled()) jumlahbulan ++;
        if (tMei.isSelected()&& tMei.isEnabled()) jumlahbulan ++;
        if (tJuni.isSelected()&& tJuni.isEnabled()) jumlahbulan ++;
        if (tJuli.isSelected()&& tJuli.isEnabled()) jumlahbulan ++;
        if (tAgustus.isSelected() && tAgustus.isEnabled()) jumlahbulan ++;
        if (tSeptember.isSelected() && tSeptember.isEnabled()) jumlahbulan ++;
        if (tOktober.isSelected() && tOktober.isEnabled()) jumlahbulan ++;
        if (tNovember.isSelected()&& tNovember.isEnabled()) jumlahbulan ++;
        if (tDesember.isSelected()&& tDesember.isEnabled()) jumlahbulan ++;
        
        if (namaa.isEmpty()|| !tJanuari.isSelected() && !tFebruari.isSelected() && !tMaret.isSelected() &&
            !tApril.isSelected() && !tMei.isSelected() && !tJuni.isSelected() &&  !tJuli.isSelected() && 
                !tAgustus.isSelected() && !tSeptember.isSelected() &&  !tOktober.isSelected() && 
                !tNovember.isSelected() && !tNovember.isSelected()){
          JOptionPane.showMessageDialog(this, "harap isi semua data !", "error", JOptionPane.ERROR_MESSAGE);
        } else {        
            try {               
                double harganyaSPP = Double.parseDouble(hargaSPP.getText()); 
                Double total = jumlahbulan * harganyaSPP;
                if (harganyaSPP < 0 ){
                     JOptionPane.showMessageDialog(this, "harga tidak boleh kurang dari 0 !", "error", JOptionPane.ERROR_MESSAGE);
                } else {
                    totalpembayarannya.setText(String.valueOf(total));
                    totalpembayarannya.setEditable(false);  
                }
            } catch(NumberFormatException e){               
               JOptionPane.showMessageDialog(this, "harap isi data dengan tepat !", "error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void tMeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMeiActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        String nama = tNama.getText();
        double harganyaSPP = Double.parseDouble(hargaSPP.getText());
 
        DefaultTableModel tablemodel = (DefaultTableModel) tabel.getModel();

        if(tJanuari.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Januari", "LUNAS"});  
            tJanuari.setEnabled(false);
            }
        if(tFebruari.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Februari", "LUNAS"});  
            tFebruari.setEnabled(false);
            }
        if(tMaret.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Maret", "LUNAS"});  
            tMaret.setEnabled(false);
            }
        if(tApril.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "April", "LUNAS"}); 
            tApril.setEnabled(false);
            }
        if(tMei.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Mei", "LUNAS"});
            tMei.setEnabled(false);
            }
        if(tJuni.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Juni", "LUNAS"}); 
            tJuni.setEnabled(false);
            }
        if(tJuli.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Juli", "LUNAS"});  
            tJuli.setEnabled(false);
            } 
        if(tAgustus.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Agustus", "LUNAS"});  
            tAgustus.setEnabled(false);
            }
        if(tSeptember.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "September", "LUNAS"});  
            tSeptember.setEnabled(false);
            }
        if(tOktober.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "tOktober", "LUNAS"}); 
            tOktober.setEnabled(false);
            }
        if(tNovember.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "November", "LUNAS"}); 
            tNovember.setEnabled(false);
            } 
        if(tDesember.isSelected()){
            tablemodel.addRow(new Object[] {nama, harganyaSPP, "Desember", "LUNAS"});  
            tDesember.setEnabled(false);
            }         

            JOptionPane.showMessageDialog(this, "Pembayaran Berhasil!", "Sukses",
               JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SimpanActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        tNama.setText("");
        totalpembayarannya.setText("");
        hargaSPP.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
       int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?",
        "Konfirmasi kembali", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);  // Keluar dari aplikasi
    }
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarSPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarSPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atas;
    private javax.swing.JPanel Bawah;
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField hargaSPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sampingkiri;
    private javax.swing.JRadioButton tAgustus;
    private javax.swing.JRadioButton tApril;
    private javax.swing.JRadioButton tDesember;
    private javax.swing.JRadioButton tFebruari;
    private javax.swing.JRadioButton tJanuari;
    private javax.swing.JRadioButton tJuli;
    private javax.swing.JRadioButton tJuni;
    private javax.swing.JRadioButton tMaret;
    private javax.swing.JRadioButton tMei;
    private javax.swing.JTextField tNama;
    private javax.swing.JRadioButton tNovember;
    private javax.swing.JRadioButton tOktober;
    private javax.swing.JRadioButton tSeptember;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField totalpembayarannya;
    // End of variables declaration//GEN-END:variables
}
